#!/usr/bin/env bash
# Private two-node Yacoin test chain (low-difficulty build, N-factor 4,
# version-7 blocks from height 0). Plan §7.4, task T-05a.
#
#   tests/testchain.sh install [BUILD_SRC_DIR]  copy yacoind + yacoin-cli into testchain/bin
#   tests/testchain.sh start                    fresh datadirs, start both nodes, wait until connected
#   tests/testchain.sh stop                     stop both nodes (keeps data)
#   tests/testchain.sh start-node N | stop-node N   one node, keeping its data (N = 1 or 2)
#   tests/testchain.sh status
#   tests/testchain.sh cli N <rpc> [args...]    yacoin-cli against node N
#   tests/testchain.sh conf N                   print the path of node N's yacoin.conf
#   tests/testchain.sh capture K                save K getwork samples to tests/data/getwork_samples.json
#
# ISOLATION. The low-difficulty build keeps mainnet's magic bytes, default
# port 7688 and fixed seeds. So every node runs with its own datadir under
# testchain/data, -connect to the other test node only (no DNS or fixed seeds),
# -listen -bind=127.0.0.1 -discover=0 -dnsseed=0 -upnp=0, and only the ports
# 27688/27689 (P2P) and 27687/27690 (RPC). The script refuses to start if a port
# is in use or the binary is not a low-difficulty build. It never touches
# /srv/yacoin or the mainnet node (RPC 7687, P2P 7688).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TC="$ROOT/testchain"
BIN="$TC/bin"
DATA="$TC/data"
YACOIND="$BIN/yacoind"
YACOINCLI="$BIN/yacoin-cli"

P2P_PORT=([1]=27688 [2]=27689)
RPC_PORT=([1]=27687 [2]=27690)
RPC_USER=testuser
RPC_PASS=testpass-not-secret
# Same consensus settings as yacoin's functional tests
# (test/functional/test_framework/util.py initialize_datadir, test_node.py).
NFACTOR=${TESTCHAIN_NFACTOR:-4}
EPOCH_INTERVAL=${TESTCHAIN_EPOCH_INTERVAL:-10}

die() { echo "testchain: $*" >&2; exit 1; }

check_node_num() { [[ "${1:-}" == 1 || "${1:-}" == 2 ]] || die "node number must be 1 or 2"; }

other() { [[ $1 == 1 ]] && echo 2 || echo 1; }

check_binaries() {
  [[ -x "$YACOIND" && -x "$YACOINCLI" ]] || die "no binaries in $BIN; run: $0 install <lowdiff build>/src"
  local v
  v="$("$YACOIND" -version 2>/dev/null | head -1)"
  [[ "$v" == *low-difficulty* ]] || die "refusing: $YACOIND is not a low-difficulty build ($v)"
}

port_in_use() { [[ -n "$(ss -ltnH "sport = :$1" 2>/dev/null)" ]]; }

cli() {
  local n=$1; shift
  local port=${RPC_PORT[$n]}
  # Hard guard: only ever talk to the test ports.
  [[ $port == 27687 || $port == 27690 ]] || die "refusing RPC to port $port"
  "$YACOINCLI" -datadir="$DATA/node$n" -conf="$DATA/node$n/yacoin.conf" \
    -rpcconnect=127.0.0.1 -rpcport="$port" "$@"
}

write_conf() {
  local n=$1 d="$DATA/node$1"
  mkdir -p "$d"
  cat >"$d/yacoin.conf" <<EOF
# generated by tests/testchain.sh (test chain only; not a secret)
rpcuser=$RPC_USER
rpcpassword=$RPC_PASS
rpcport=${RPC_PORT[$n]}
port=${P2P_PORT[$n]}
server=1
EOF
}

node_pid() { local f="$DATA/node$1/yacoind.pid"; [[ -f $f ]] && cat "$f" || true; }

node_running() { local p; p="$(node_pid "$1")"; [[ -n $p ]] && kill -0 "$p" 2>/dev/null; }

start_node() {
  local n=$1 d="$DATA/node$1" o
  o=$(other "$n")
  node_running "$n" && die "node $n already running (pid $(node_pid "$n"))"
  for p in "${P2P_PORT[$n]}" "${RPC_PORT[$n]}"; do
    port_in_use "$p" && die "refusing: port $p is already in use"
  done
  [[ -f "$d/yacoin.conf" ]] || write_conf "$n"
  # Settings: functional-test defaults + network isolation (see header).
  setsid nohup "$YACOIND" \
    -datadir="$d" -conf="$d/yacoin.conf" -pid="$d/yacoind.pid" -daemon=0 \
    -server=1 -rpcbind=127.0.0.1 -rpcallowip=127.0.0.1 -rpcport="${RPC_PORT[$n]}" \
    -port="${P2P_PORT[$n]}" -listen=1 -bind=127.0.0.1 -discover=0 -dnsseed=0 \
    -upnp=0 -listenonion=0 -connect="127.0.0.1:${P2P_PORT[$o]}" \
    -nFactorAtHardfork="$NFACTOR" -testnetNewLogicBlockNumber=0 \
    -epochinterval="$EPOCH_INTERVAL" -checkblocks=8 -logtimestamps=1 -logtimemicros \
    -printtoconsole=0 -uacomment="cpuminer-testnode$n" \
    >"$d/stdout.log" 2>&1 </dev/null &
  echo $! >"$d/yacoind.pid"
  local i
  for i in $(seq 1 120); do
    if cli "$n" getblockcount >/dev/null 2>&1; then
      echo "node $n up: P2P ${P2P_PORT[$n]}, RPC ${RPC_PORT[$n]}, pid $(node_pid "$n")"
      return 0
    fi
    node_running "$n" || { tail -20 "$d/stdout.log" >&2; die "node $n exited during start-up"; }
    sleep 1
  done
  die "node $n did not answer RPC within 120 s"
}

stop_node() {
  local n=$1 p i
  node_running "$n" || { echo "node $n not running"; return 0; }
  p="$(node_pid "$n")"
  cli "$n" stop >/dev/null 2>&1 || kill "$p"
  for i in $(seq 1 60); do
    kill -0 "$p" 2>/dev/null || { echo "node $n stopped"; rm -f "$DATA/node$n/yacoind.pid"; return 0; }
    sleep 1
  done
  kill -9 "$p" 2>/dev/null || true
  rm -f "$DATA/node$n/yacoind.pid"
  echo "node $n killed after 60 s"
}

wait_connected() {
  local i
  for i in $(seq 1 60); do
    if [[ "$(cli 1 getconnectioncount 2>/dev/null || echo 0)" -ge 1 &&
          "$(cli 2 getconnectioncount 2>/dev/null || echo 0)" -ge 1 ]]; then
      echo "nodes connected"
      return 0
    fi
    sleep 1
  done
  die "nodes did not connect within 60 s"
}

status() {
  local n
  for n in 1 2; do
    if node_running "$n"; then
      echo "node $n: running pid $(node_pid "$n"), blocks $(cli "$n" getblockcount 2>/dev/null || echo '?')," \
           "connections $(cli "$n" getconnectioncount 2>/dev/null || echo '?')"
    else
      echo "node $n: stopped"
    fi
  done
}

capture() {
  # Captures K getwork responses from node 1 together with the
  # raw_block_header_hex line the node logs for the same call (plan §7.2).
  local k=${1:-3} out="$ROOT/tests/data/getwork_samples.json" log="$DATA/node1/debug.log" i
  command -v python3 >/dev/null || die "python3 needed for capture"
  mkdir -p "$ROOT/tests/data"
  local tmp; tmp="$(mktemp -d)"
  for i in $(seq 1 "$k"); do
    local before; before=$(wc -l <"$log")
    cli 1 getwork >"$tmp/gw$i.json"
    sleep 0.5
    tail -n +"$((before + 1))" "$log" >"$tmp/log$i.txt"
    cli 1 getmininginfo >"$tmp/mi$i.json"
    cli 1 getbestblockhash >"$tmp/tip$i.txt"
  done
  python3 - "$tmp" "$k" "$out" "$("$YACOIND" -version | head -1)" <<'PY'
import json, re, sys
tmp, k, out, ver = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
samples = []
for i in range(1, k + 1):
    gw = json.load(open(f"{tmp}/gw{i}.json"))
    log = open(f"{tmp}/log{i}.txt").read()
    def grab(name):
        m = re.findall(name + r" = ([^,\n]+)", log)
        return m[-1].strip() if m else None
    mi = json.load(open(f"{tmp}/mi{i}.json"))
    samples.append({
        "data": gw["data"], "target": gw["target"],
        "raw_block_header_hex": grab("raw_block_header_hex"),
        "log": {"nVersion": int(grab(r"pblock->nVersion")), "hashPrevBlock": grab(r"pblock->hashPrevBlock"),
                "hashMerkleRoot": grab(r"pblock->hashMerkleRoot"), "nTime": int(grab(r"pblock->nTime")),
                "nBits": int(grab(r"pblock->nBits")), "nNonce": int(grab(r"pblock->nNonce")),
                "target_BE": grab("target_BE")},
        "bestblockhash": open(f"{tmp}/tip{i}.txt").read().strip(),
        "height": mi["blocks"], "Nfactor": mi["Nfactor"], "N": mi["N"],
    })
json.dump({"source": "tests/testchain.sh capture (low-difficulty test chain, node 1)",
           "yacoind": ver, "samples": samples}, open(out, "w"), indent=1)
print(f"wrote {len(samples)} samples to {out}")
PY
  rm -rf "$tmp"
}

cmd=${1:-}
shift || true
case "$cmd" in
  install)
    src=${1:-$HOME/.cache/yacoin-build-P0-50/build-lowdiff/src}
    mkdir -p "$BIN"
    cp -p "$src/yacoind" "$src/yacoin-cli" "$BIN/"
    check_binaries
    "$YACOIND" -version | head -1
    (cd "$BIN" && sha256sum yacoind yacoin-cli)
    ;;
  start)
    check_binaries
    for n in 1 2; do node_running "$n" && die "node $n already running; stop first"; done
    for p in "${P2P_PORT[@]}" "${RPC_PORT[@]}"; do port_in_use "$p" && die "refusing: port $p is already in use"; done
    rm -rf "$DATA"
    start_node 1
    start_node 2
    wait_connected
    cli 1 getmininginfo | grep -E '"(blocks|Nfactor|N)"'
    ;;
  stop) stop_node 1; stop_node 2 ;;
  start-node) check_node_num "${1:-}"; check_binaries; start_node "$1" ;;
  stop-node) check_node_num "${1:-}"; stop_node "$1" ;;
  status) status ;;
  cli) check_node_num "${1:-}"; n=$1; shift; cli "$n" "$@" ;;
  conf) check_node_num "${1:-}"; echo "$DATA/node$1/yacoin.conf" ;;
  capture) capture "${1:-3}" ;;
  *) sed -n '2,15p' "$0"; exit 2 ;;
esac
